zk:
  image: pyxixi2012/zookeeper:3.4.6
  restart: always
  ports:
    - "192.168.1.215:2181:2181"
    - "192.168.1.215:2888:2888"
    - "192.168.1.215:3888:3888"
  environment:
    ZOOKEEPER_INSTANCES: zk-node-0,zk-node-1,zk-node-2
    SERVICE_NAME: zookeeper
    CONTAINER_NAME: zk-node-0
    ZOOKEEPER_SERVER_IDS: zk-node-0:1,zk-node-1:2,zk-node-2:3
    ZOOKEEPER_ZK_NODE_0_HOST: 192.168.1.215
    ZOOKEEPER_ZK_NODE_0_CLIENT_PORT: 2181
    ZOOKEEPER_ZK_NODE_0_PEER_PORT: 2888
    ZOOKEEPER_ZK_NODE_0_LEADER_ELECTION_PORT: 3888
    ZOOKEEPER_ZK_NODE_1_HOST: 192.168.1.208
    ZOOKEEPER_ZK_NODE_1_CLIENT_PORT: 2181
    ZOOKEEPER_ZK_NODE_1_PEER_PORT: 2888
    ZOOKEEPER_ZK_NODE_1_LEADER_ELECTION_PORT: 3888
    ZOOKEEPER_ZK_NODE_2_HOST: 192.168.1.138
    ZOOKEEPER_ZK_NODE_2_CLIENT_PORT: 2181
    ZOOKEEPER_ZK_NODE_2_PEER_PORT: 2888
    ZOOKEEPER_ZK_NODE_2_LEADER_ELECTION_PORT: 3888
