kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.1.215
    KAFKA_ZOOKEEPER_CONNECT: 192.168.1.215
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
